apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment       # ✅ reuse existing deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 842871321276.dkr.ecr.us-east-1.amazonaws.com/weather-dashboard:latest
        ports:
        - containerPort: 5000
        env:
        - name: WEATHER_API_KEY
          value: "d302e90f91ba81bd357cd4b6af985553"   # 🔑 your API key
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service          # ✅ reuse existing service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
