apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dashboard-deployment
  labels:
    app: weather-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-dashboard
  template:
    metadata:
      labels:
        app: weather-dashboard
    spec:
      containers:
      - name: weather-dashboard
        image: 842871321276.dkr.ecr.us-east-1.amazonaws.com/project/weather-dashboard:latest
        ports:
        - containerPort: 5000
        env:
        - name: WEATHER_API_KEY
          value: "*************"   # 🔑 replace with your real API key
---
apiVersion: v1
kind: Service
metadata:
  name: weather-dashboard-service
spec:
  selector:
    app: weather-dashboard
  ports:
    - protocol: TCP
      port: 80        # Exposed service port
      targetPort: 5000 # Flask app port
  type: LoadBalancer
